const config = {
    level: "movie",
    time: 2000
}

const levels = {
    "movie": [
        {
            src: "./mov/1.mp4",
            category: "it",
            rightAnswer: ["фишинг", "fishing"],
            factor: 10,
        },
        {
            src: "./mov/2.mp4",
            category: "it",
            rightAnswer: ["прототип", "prototype"],
            factor: 10,
        },
        {
            src: "./mov/3.mp4",
            category: "back",
            rightAnswer: ["демон", "daemon", "демоны"],
            factor: 20,
        },
        {
            src: "./mov/4.mp4",
            category: "front",
            rightAnswer: ["progress bar", "прогресбар", "progressbar", "прогресс-бар", "прогресс бар"],
            factor: 10,
        },
        {
            src: "./mov/5.mp4",
            category: "common",
            rightAnswer: ["касание", "точка касания"],
            factor: 20,
        },
        {
            src: "./mov/6.mp4",
            category: "common",
            rightAnswer: ["статус", "status"],
            factor: 20,
        },
        {
            src: "./mov/7.mp4",
            category: "it",
            rightAnswer: ["брутфорс", "brute force", "полный перебор", "метод грубой силы", "bruteforce"],
            factor: 10,
        },
        {
            src: "./mov/8.mp4",
            category: "it",
            rightAnswer: ["wrapper", "обертка", "обёртка"],
            factor: 10,
        },
        {
            src: "./mov/9.mp4",
            category: "common",
            rightAnswer: ["рисование", "творчество"],
            factor: 10,
        },
        {
            src: "./mov/10.mp4",
            category: "testing",
            rightAnswer: ["диаграмма состояний"],
            factor: 30,
        },
        {
            src: "./mov/11.mp4",
            category: "it",
            rightAnswer: ["контейнер", "container"],
            factor: 20,
        },
        {
            src: "./mov/12.mp4",
            category: "common",
            rightAnswer: ["лабиринт"],
            factor: 10,
        },
        {
            src: "./mov/13.mp4",
            category: "it",
            rightAnswer: ["патч", "patch"],
            factor: 10,
        },
        {
            src: "./mov/14.mp4",
            category: "it",
            rightAnswer: ["песочница", "sandbox"],
            factor: 10,
        },
        {
            src: "./mov/15.mp4",
            category: "common",
            rightAnswer: ["рутина"],
            factor: 20,
        },
        {
            src: "./mov/16.mp4",
            category: "it",
            rightAnswer: ["запрос"],
            factor: 20,
        },
        {
            src: "./mov/17.mp4",
            category: "common",
            rightAnswer: ["торрент", "torrent"],
            factor: 10,
        },
        {
            src: "./mov/18.mp4",
            category: "it",
            rightAnswer: ["бот", "bot", "боты"],
            factor: 10,
        },
        {
            src: "./mov/19.mp4",
            category: "it",
            rightAnswer: ["сертификат", "серт", "серты", "сертификаты"],
            factor: 30,
        },
        {
            src: "./mov/20.mp4",
            category: "common",
            rightAnswer: ["облако"],
            factor: 20,
        },
        {
            src: "./mov/21.mp4",
            category: "it",
            rightAnswer: ["шифрование", "encryption", "шифруешь", "шифровать"],
            factor: 10,
        },
        {
            src: "./mov/22.mp4",
            category: "common",
            rightAnswer: ["рабочий стол", "десктоп", "desctop"],
            factor: 10,
        },
        {
            src: "./mov/23.mp4",
            category: "it",
            rightAnswer: ["алгоритм"],
            factor: 30,
        },
        {
            src: "./mov/24.mp4",
            category: "testing",
            rightAnswer: ["проверка", "с проверкой", "проверкой"],
            factor: 20,
        },
        {
            src: "./mov/25.mp4",
            category: "it",
            rightAnswer: ["зависимости", "зависимость", "dependences", "dependence"],
            factor: 20,
        },
        {
            src: "./mov/26.mp4",
            category: "devops",
            rightAnswer: ["установка", "деплой", "deploy", "установили", "задеплоили", "релиз", "зарелизили", "release"],
            factor: 20,
        },
        {
            src: "./mov/27.mp4",
            category: "it",
            rightAnswer: ["композиция"],
            factor: 30,
        },
        {
            src: "./mov/28.mp4",
            category: "devops",
            rightAnswer: ["логирование", "логгирование"],
            factor: 20,
        },
        {
            src: "./mov/29.mp4",
            category: "front",
            rightAnswer: ["react", "реакт"],
            factor: 30,
        },
        {
            src: "./mov/30.mp4",
            category: "front",
            rightAnswer: ["дом", "dom"],
            factor: 30,
        },
        {
            src: "./mov/31.mp4",
            category: "common",
            rightAnswer: ["ограничитель", "ограничение"],
            factor: 30,
        },
        {
            src: "./mov/32.mp4",
            category: "it",
            rightAnswer: ["документ", "document"],
            factor: 20,
        },
        {
            src: "./mov/33.mp4",
            category: "front",
            rightAnswer: ["модальное окно", "модалка", "modal", "modal window", "modal box"],
            factor: 20,
        },
        {
            src: "./mov/34.mp4",
            category: "it",
            rightAnswer: ["уязвимость", "vulnerability"],
            factor: 10,
        },
        {
            src: "./mov/35.mp4",
            category: "it",
            rightAnswer: ["фабрика", "factory"],
            factor: 10,
        },
        {
            src: "./mov/36.mp4",
            category: "it",
            rightAnswer: ["компиляция", "compilation"],
            factor: 20,
        },
        {
            src: "./mov/37.mp4",
            category: "it",
            rightAnswer: ["паттерн", "шаблон", "pattern"],
            factor: 30,
        },
        {
            src: "./mov/38.mp4",
            category: "it",
            rightAnswer: ["метаданные", "мета данные", "мета-данные", "metadata", "meta data", "метадата"],
            factor: 30,
        },
        {
            src: "./mov/39.mp4",
            category: "front",
            rightAnswer: ["верстка", "вёрстка"],
            factor: 20,
        },
        {
            src: "./mov/40.mp4",
            category: "front",
            rightAnswer: ["hosting", "хостинг"],
            factor: 20,
        },
        {
            src: "./mov/41.mp4",
            category: "it",
            rightAnswer: ["динамический", "dinamic"],
            factor: 20,
        },
        {
            src: "./mov/42.mp4",
            category: "devoops",
            rightAnswer: ["конфигурация", "configuration"],
            factor: 20,
        },
        {
            src: "./mov/43.mp4",
            category: "back",
            rightAnswer: ["core", "ядро"],
            factor: 10,
        },
        {
            src: "./mov/44.mp4",
            category: "it",
            rightAnswer: ["solid", "солид"],
            factor: 20,
        },
        {
            src: "./mov/45.mp4",
            category: "it",
            rightAnswer: ["rpc"],
            factor: 30,
        },
        {
            src: "./mov/46.mp4",
            category: "it",
            rightAnswer: ["mapping", "конвертация", "маппинг"],
            factor: 20,
        },
        {
            src: "./mov/47.mp4",
            category: "devoops",
            rightAnswer: ["кластер", "cluster"],
            factor: 10,
        },
        {
            src: "./mov/48.mp4",
            category: "it",
            rightAnswer: ["синглтон", "singleton"],
            factor: 20,
        },
        {
            src: "./mov/49.mp4",
            category: "common",
            rightAnswer: ["модератор", "модерирует", "модерировать"],
            factor: 10,
        },
        {
            src: "./mov/50.mp4",
            category: "it",
            rightAnswer: ["интерфейс", "interface"],
            factor: 10,
        },
        {
            src: "./mov/51.mp4",
            category: "it",
            rightAnswer: ["инъекция", "injection", "иньекция"],
            factor: 10,
        },
        {
            src: "./mov/52.mp4",
            category: "it",
            rightAnswer: ["event", "ивент", "евент", "эвент"],
            factor: 30,
        },
        {
            src: "./mov/53.mp4",
            category: "it",
            rightAnswer: ["контракт"],
            factor: 20,
        },
        {
            src: "./mov/54.mp4",
            category: "it",
            rightAnswer: ["фреймворк", "framework", "фреймворки"],
            factor: 20,
        },
        {
            src: "./mov/55.mp4",
            category: "common",
            rightAnswer: ["розетка"],
            factor: 10,
        },
        {
            src: "./mov/56.mp4",
            category: "common",
            rightAnswer: ["монитор", "моник", "monitor"],
            factor: 10,
        },
        {
            src: "./mov/57.mp4",
            category: "it",
            rightAnswer: ["слушатель", "listener"],
            factor: 30,
        },
        {
            src: "./mov/58.mp4",
            category: "it",
            rightAnswer: ["callback", "коллбэк", "колбэк", "колбек", "коллбек"],
            factor: 30,
        },
        {
            src: "./mov/59.mp4",
            category: "common",
            rightAnswer: ["семантика"],
            factor: 20,
        },
        {
            src: "./mov/60.mp4",
            category: "it",
            rightAnswer: ["инкапсуляция"],
            factor: 20,
        },
        {
            src: "./mov/61.mp4",
            category: "it",
            rightAnswer: ["репозиторий", "репа", "repository"],
            factor: 20,
        },
        {
            src: "./mov/62.mp4",
            category: "back",
            rightAnswer: ["воркер", "обработчик", "worker"],
            factor: 30,
        },
        {
            src: "./mov/63.mp4",
            category: "it",
            rightAnswer: ["чистый код", "clean code"],
            factor: 20,
        },
        {
            src: "./mov/64.mp4",
            category: "it",
            rightAnswer: ["учетка", "учётка", "учетная запись", "учётная запись"],
            factor: 10,
        },
        {
            src: "./mov/65.mp4",
            category: "front",
            rightAnswer: ["подвал", "футер", "footer"],
            factor: 20,
        },
        {
            src: "./mov/66.mp4",
            category: "devops",
            rightAnswer: ["метрики", "metrics"],
            factor: 20,
        },
        {
            src: "./mov/67.mp4",
            category: "devops",
            rightAnswer: ["proxy", "прокси", "прокся"],
            factor: 10,
        },
        {
            src: "./mov/68.mp4",
            category: "it",
            rightAnswer: ["хакатон", "hachaton"],
            factor: 10,
        },
        {
            src: "./mov/69.mp4",
            category: "common",
            rightAnswer: ["ретроспектива", "ретро"],
            factor: 20,
        },
        {
            src: "./mov/70.mp4",
            category: "common",
            rightAnswer: ["капча", "captcha", "капчей"],
            factor: 20,
        }]
}